In [2]:
!which python3

/home/ml02/Downloads/PyTorch/PyTorch/bin/python3


In [4]:
!python3 --version

Python 3.10.12


In [1]:
import os

In [5]:
import torch

In [6]:
print(torch.cuda.is_available())

True


In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[7.9553e-01, 8.8821e-01, 6.2842e-01],
        [6.3148e-01, 8.8429e-04, 3.0355e-01],
        [3.4025e-01, 7.5899e-01, 4.5442e-02],
        [3.2514e-01, 8.8553e-02, 9.0668e-01],
        [3.4949e-01, 8.3783e-01, 4.3968e-01]])


In [8]:
print(torch.__version__)

2.5.1+cu121


In [9]:
print(torch.cuda.get_device_name(0))

NVIDIA GeForce RTX 4060 Laptop GPU


In [58]:
# TO create an empty tensor

torch.empty(2,3)

tensor([[-4.1924e-19,  3.5632e-41, -3.0557e-28],
        [ 4.5549e-41,  8.9683e-44,  0.0000e+00]])

In [11]:
type(torch.empty(2,3))

torch.Tensor

In [62]:
torch.empty(2,3)

tensor([[-3.0899e-19,  3.5632e-41, -4.3474e-19],
        [ 3.5632e-41,  1.1210e-43,  0.0000e+00]])

In [13]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
torch.rand(2,3)

tensor([[0.4148, 0.1425, 0.2925],
        [0.8256, 0.6557, 0.1438]])

In [25]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [26]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [20]:
torch.tensor([1,2,3,4])

tensor([1, 2, 3, 4])

In [27]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [29]:
torch.linspace(0,10,10) # Same linearly separated points b/w a range inclusive

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [30]:
torch.eye(3) #identity tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [32]:
torch.full((3,3),1) # Populates a given shape of tensor with a particular value

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [35]:
# tensor shapes

x = torch.tensor([[[1,2,3,]]])
print(x.shape)

torch.Size([1, 1, 3])


In [49]:
# To create a empty tensor with a particular shape

torch.empty_like(x)

tensor([[[139610357345664, 109215129354192, 139605924031472]]])

In [63]:
torch.zeros_like(x)

tensor([[[0, 0, 0]]])

In [64]:
torch.ones_like(x)

tensor([[[1, 1, 1]]])

In [66]:
torch.rand_like(x) # TO generate this we have to implicitly declare the data type (here float as rand generates float)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [67]:
x.dtype

torch.int64

In [76]:
torch.tensor([1,2,3,4],dtype=torch.uint8)

tensor([1, 2, 3, 4], dtype=torch.uint8)

In [79]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0])
x_quant = torch.quantize_per_tensor(x, scale=1.0, zero_point=0, dtype=torch.quint4x2)
x_quant

tensor([1., 2., 3., 4.], size=(4,), dtype=torch.quint4x2,
       quantization_scheme=torch.per_tensor_affine, scale=1.0, zero_point=0)

In [80]:
torch.tensor([1,2,3,4],dtype=torch.cuda.IntTensor)

TypeError: tensor(): argument 'dtype' must be torch.dtype, not torch.tensortype

In [81]:
x = torch.tensor([1, 2, 3, 4])
print(x.device)  # Output: cpu


cpu


In [82]:
x = torch.tensor([1, 2, 3, 4], device='cuda')  # Goes to GPU
print(x.device)  # Output: cuda:0


cuda:0


In [84]:
x = torch.tensor([1, 2, 3, 4])
x = x.to('cuda')
x.device

device(type='cuda', index=0)

In [85]:
x = torch.cuda.FloatTensor(3, 2)  # 3x2 float tensor on GPU with uninitialized values


/tmp/ipykernel_92562/956257627.py:1: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:78.)
  x = torch.cuda.FloatTensor(3, 2)  # 3x2 float tensor on GPU with uninitialized values


In [104]:
x = torch.tensor([[1,2,3],[2,3,4]], dtype=torch.float64)
x

tensor([[1., 2., 3.],
        [2., 3., 4.]], dtype=torch.float64)

In [105]:
x = x.to(torch.int)

In [93]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])

In [108]:
# Scalar operations
print(x.dtype)

print(x)

torch.int32
tensor([[1, 2, 3],
        [2, 3, 4]], dtype=torch.int32)


In [109]:
print(x+2)

print(x-2)

tensor([[3, 4, 5],
        [4, 5, 6]], dtype=torch.int32)
tensor([[-1,  0,  1],
        [ 0,  1,  2]], dtype=torch.int32)


In [110]:
print(x*2)

print(x/2)

tensor([[2, 4, 6],
        [4, 6, 8]], dtype=torch.int32)
tensor([[0.5000, 1.0000, 1.5000],
        [1.0000, 1.5000, 2.0000]])


In [111]:
print((x*100)//2)

print(((x*100)//3)%2)

tensor([[ 50, 100, 150],
        [100, 150, 200]], dtype=torch.int32)
tensor([[1, 0, 0],
        [0, 0, 1]], dtype=torch.int32)


In [112]:
print(x**2)

tensor([[ 1,  4,  9],
        [ 4,  9, 16]], dtype=torch.int32)


In [120]:
# Element Wise Ops

x = torch.rand_like(x, dtype=torch.float32)
y = torch.randn_like(x, dtype=torch.float32)

print(x,y)

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]]) tensor([[-0.5687,  1.2580, -1.5890],
        [-1.1208,  0.8423,  0.1744]])


In [121]:
x+y

tensor([[-0.0372,  1.4167, -0.9348],
        [-0.7930,  1.4955,  0.5702]])

In [122]:
x-y

tensor([[ 1.1001, -1.0993,  2.2431],
        [ 1.4486, -0.1891,  0.2214]])

In [124]:
x*y

tensor([[-0.3022,  0.1997, -1.0395],
        [-0.3674,  0.5502,  0.0690]])

In [125]:
x/y

tensor([[-0.9346,  0.1262, -0.4117],
        [-0.2925,  0.7755,  2.2695]])

In [127]:
(x*100)//y

tensor([[-94.,  12., -42.],
        [-30.,  77., 226.]])

In [128]:
x%y

tensor([[-0.0372,  0.1587, -0.9348],
        [-0.7930,  0.6532,  0.0470]])

In [130]:
torch.abs(x%y)

tensor([[0.0372, 0.1587, 0.9348],
        [0.7930, 0.6532, 0.0470]])

In [134]:
torch.round(torch.abs(x%y))

tensor([[0., 0., 1.],
        [1., 1., 0.]])

In [135]:
torch.ceil(x%y)

tensor([[-0., 1., -0.],
        [-0., 1., 1.]])

In [136]:
torch.floor(x%y)

tensor([[-1.,  0., -1.],
        [-1.,  0.,  0.]])

In [142]:
torch.clamp(x%y, min=-0.02, max=0.5)

tensor([[-0.0200,  0.1587, -0.0200],
        [-0.0200,  0.5000,  0.0470]])

In [145]:
# Reduction op
e = torch.randint(size = (2,3), low=5, high=10, device='cuda')
print(e)

tensor([[8, 5, 8],
        [8, 9, 9]], device='cuda:0')


In [146]:
torch.sum(e)

tensor(47, device='cuda:0')

In [147]:
print(torch.sum(e, dim=0)) # Sum along each column
print(torch.sum(e, dim=1)) # Sum along each row

tensor([16, 14, 17], device='cuda:0')
tensor([21, 26], device='cuda:0')


In [153]:
print(torch.mean(e, dtype = torch.float)) # Works with dtype = float
print(torch.mean(e, dtype = torch.float, dim = 0))

tensor(7.8333, device='cuda:0')
tensor([8.0000, 7.0000, 8.5000], device='cuda:0')


In [158]:
print(torch.median(e)) # Works with dtype = float

tensor(8, device='cuda:0')


In [159]:
print(torch.median(e, dim = 0))

torch.return_types.median(
values=tensor([8, 5, 8], device='cuda:0'),
indices=tensor([0, 0, 0], device='cuda:0'))


In [160]:
print(torch.min(e)) # Works with dtype = float
print(torch.max(e, dim = 0))

tensor(5, device='cuda:0')
torch.return_types.max(
values=tensor([8, 9, 9], device='cuda:0'),
indices=tensor([0, 1, 1], device='cuda:0'))


In [162]:
# unpacking

values, indices = torch.min(e, dim=0)

print(f'The values are: {values}')
print(f'The indices are: {indices}')

The values are: tensor([8, 5, 8], device='cuda:0')
The indices are: tensor([0, 0, 0], device='cuda:0')


In [170]:
# Variance
## std and var only support floating point and complex dtypes
torch.var(e.to(torch.float))

tensor(2.1667, device='cuda:0')

In [172]:
torch.var(e.float())

tensor(2.1667, device='cuda:0')

In [173]:
torch.var(e.float().cuda())

tensor(2.1667, device='cuda:0')

In [174]:
torch.var(e.float().cpu())

tensor(2.1667)

In [177]:
e

tensor([[8, 5, 8],
        [8, 9, 9]], device='cuda:0')

In [175]:
torch.argmax(e) # Returns the pos of the maximum elem

tensor(4, device='cuda:0')

In [176]:
torch.argmin(e)

tensor(1, device='cuda:0')

In [180]:
# Matrix Multiplication
print(x.shape)
torch.matmul(x,y.view(3,2)) # Reshaping the y tensor so that mat mul can take place

torch.Size([2, 3])


tensor([[-0.0034,  0.6048],
        [-0.8909, -0.2507]])

In [188]:
torch.dot(x.view(-1),y.view(-1))  # Squeezing both to 1D tensor

tensor(-0.8902)

In [190]:
y

tensor([[-0.5687,  1.2580, -1.5890],
        [-1.1208,  0.8423,  0.1744]])

In [189]:
torch.transpose(y, 0, 1)

tensor([[-0.5687, -1.1208],
        [ 1.2580,  0.8423],
        [-1.5890,  0.1744]])

In [192]:
torch.transpose(y, 1, 0)

tensor([[-0.5687, -1.1208],
        [ 1.2580,  0.8423],
        [-1.5890,  0.1744]])

In [193]:
torch.unsqueeze(y, 1)

tensor([[[-0.5687,  1.2580, -1.5890]],

        [[-1.1208,  0.8423,  0.1744]]])

In [194]:
x

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])

In [196]:
# Create 1x3 row of random numbers (same dtype and device as x)
rand_row = torch.randn(1, 3, dtype=x.dtype, device=x.device)

print(rand_row)

# Concatenate along the row axis (dim=0)
x_3x3 = torch.cat((x, rand_row), dim=0)

print(x_3x3)


tensor([[ 0.7343, -0.6708,  2.7421]])
tensor([[ 0.5315,  0.1587,  0.6542],
        [ 0.3278,  0.6532,  0.3958],
        [ 0.7343, -0.6708,  2.7421]])


In [197]:
torch.det(x_3x3)

tensor(0.5389)

In [198]:
torch.inverse(x_3x3)

tensor([[ 3.8164, -1.6219, -0.6763],
        [-1.1286,  1.8129,  0.0075],
        [-1.2981,  0.8778,  0.5476]])

In [201]:
print(x)
print(y)

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])
tensor([[-0.5687,  1.2580, -1.5890],
        [-1.1208,  0.8423,  0.1744]])


In [200]:
# Comparison Operations

x > y

tensor([[ True, False,  True],
        [ True, False,  True]])

In [202]:
x<y

tensor([[False,  True, False],
        [False,  True, False]])

In [203]:
x==y

tensor([[False, False, False],
        [False, False, False]])

In [204]:
x!=y

tensor([[True, True, True],
        [True, True, True]])

In [205]:
x>=y

tensor([[ True, False,  True],
        [ True, False,  True]])

In [208]:
x<=y

tensor([[False,  True, False],
        [False,  True, False]])

In [240]:
# Special Funcs
k = torch.randint(size=(3,3), low = -1, high =11)
k

tensor([[ 7,  5, 10],
        [ 2,  0,  1],
        [ 5, -1,  9]])

In [241]:
torch.log(k)

tensor([[1.9459, 1.6094, 2.3026],
        [0.6931,   -inf, 0.0000],
        [1.6094,    nan, 2.1972]])

In [242]:
torch.exp(k)

tensor([[1.0966e+03, 1.4841e+02, 2.2026e+04],
        [7.3891e+00, 1.0000e+00, 2.7183e+00],
        [1.4841e+02, 3.6788e-01, 8.1031e+03]])

In [243]:
torch.sqrt(k)

tensor([[2.6458, 2.2361, 3.1623],
        [1.4142, 0.0000, 1.0000],
        [2.2361,    nan, 3.0000]])

In [244]:
torch.sigmoid(k)

tensor([[0.9991, 0.9933, 1.0000],
        [0.8808, 0.5000, 0.7311],
        [0.9933, 0.2689, 0.9999]])

In [245]:
torch.softmax(k.to(float), dim = 0) # Expects tensor dtype as float

tensor([[8.7560e-01, 9.9087e-01, 7.3099e-01],
        [5.8998e-03, 6.6764e-03, 9.0212e-05],
        [1.1850e-01, 2.4561e-03, 2.6892e-01]], dtype=torch.float64)

In [246]:
torch.relu(k)

tensor([[ 7,  5, 10],
        [ 2,  0,  1],
        [ 5,  0,  9]])

In [250]:
# Inplace Operators ('_' underscore defines inplace operators)
print(x)
print(y)
print(x.add(y))

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])
tensor([[-0.5687,  1.2580, -1.5890],
        [-1.1208,  0.8423,  0.1744]])
tensor([[-0.0372,  1.4167, -0.9348],
        [-0.7930,  1.4955,  0.5702]])


In [251]:
print(x)
print(x.add_(y))
print(x)

tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])
tensor([[-0.0372,  1.4167, -0.9348],
        [-0.7930,  1.4955,  0.5702]])
tensor([[-0.0372,  1.4167, -0.9348],
        [-0.7930,  1.4955,  0.5702]])


In [255]:
print(k)

tensor([[ 7,  5, 10],
        [ 2,  0,  1],
        [ 5, -1,  9]])


In [256]:
print(torch.relu(k))

tensor([[ 7,  5, 10],
        [ 2,  0,  1],
        [ 5,  0,  9]])


In [258]:
print(torch.relu_(k)) # Or do k.relu_()
print(k)

tensor([[ 7,  5, 10],
        [ 2,  0,  1],
        [ 5,  0,  9]])
tensor([[ 7,  5, 10],
        [ 2,  0,  1],
        [ 5,  0,  9]])


In [259]:
# copying a tensor

x = torch.rand(2,3)
print(x)
y = x
print(y)

tensor([[0.6161, 0.7583, 0.5907],
        [0.3219, 0.7610, 0.7628]])
tensor([[0.6161, 0.7583, 0.5907],
        [0.3219, 0.7610, 0.7628]])


In [260]:
x[0][0] = 0
print(x)
print(y)

tensor([[0.0000, 0.7583, 0.5907],
        [0.3219, 0.7610, 0.7628]])
tensor([[0.0000, 0.7583, 0.5907],
        [0.3219, 0.7610, 0.7628]])


In [262]:
id(x) == id(y) # The memory they are pointing to is the same, so if we change one the other will get changed

True

In [263]:
y[0][0] = 1
print(x)
print(y)

tensor([[1.0000, 0.7583, 0.5907],
        [0.3219, 0.7610, 0.7628]])
tensor([[1.0000, 0.7583, 0.5907],
        [0.3219, 0.7610, 0.7628]])


In [265]:
# Copying a tensor but both will be pointing to different locations

a = torch.rand(2,3)
b = a.clone()
print(id(a))
print(id(b))

139604928582880
139605631292400


In [271]:
import copy
a = torch.rand(2,3)
b = copy.deepcopy(a)
print(id(a))
print(id(b))
print(type(b))

139604926220704
139609593727472
<class 'torch.Tensor'>


In [273]:
import time

size = 10000

matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
end_time = time.time()
print(f'CPU time to multiply two 10000*10000 matrix is: {end_time - start_time}')

matrix_gpu1 = torch.randn(size, size, device='cuda')
matrix_gpu2 = torch.randn(size, size, device='cuda')

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
end_time = time.time()
print(f'GPU time to multiply two 10000*10000 matrix is: {end_time - start_time}')

CPU time to multiply two 10000*10000 matrix is: 6.964176893234253
GPU time to multiply two 10000*10000 matrix is: 0.0798025131225586


In [276]:
# Reshaping Tensors

a = torch.ones(4,4)
print(a)

a = a.reshape(2,2,2,2)
print(a)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])


In [277]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [278]:
b = torch.randn(3,4,2)
print(b)

tensor([[[ 1.7058,  1.1128],
         [-1.2113,  0.5597],
         [-0.6295, -0.3746],
         [ 1.3099,  1.1715]],

        [[ 0.3737, -0.4780],
         [-1.2095,  0.5958],
         [ 0.3351,  0.9003],
         [ 1.8559, -0.4290]],

        [[-0.1474,  0.3337],
         [ 0.0076,  2.3507],
         [-1.7512, -0.0312],
         [ 0.0649,  0.4850]]])


In [283]:
b.permute(2,0,1) # takes the indices of the shape

tensor([[[ 1.7058, -1.2113, -0.6295,  1.3099],
         [ 0.3737, -1.2095,  0.3351,  1.8559],
         [-0.1474,  0.0076, -1.7512,  0.0649]],

        [[ 1.1128,  0.5597, -0.3746,  1.1715],
         [-0.4780,  0.5958,  0.9003, -0.4290],
         [ 0.3337,  2.3507, -0.0312,  0.4850]]])

In [281]:
b.permute(2,0,1).shape

torch.Size([2, 3, 4])

In [296]:
a = torch.randn(226,226,3)
a.unsqueeze(3).shape #Adds dimension to the existing shape at a particular position

# unsqueeze is helpful in a scenario where if one single image is passed to a model, as a model takes images in batches
# e.g. n*x*y*c where n is the batch number then in that case we can convert the single image of dim x*y*c into
# a single batch like 1*x*y*c using unsqueeze

torch.Size([226, 226, 3, 1])

In [303]:
# Squeeze only removes the dimension if its size is 1.
#
# If tensor.shape[dim] != 1, it leaves the tensor unchanged.

print(a.shape)
print(a.squeeze(1).shape)

torch.Size([226, 226, 3])
torch.Size([226, 226, 3])


In [306]:
a = torch.rand(1,20)
print(a.squeeze(0).shape)

torch.Size([20])


In [305]:
#  To remove all dimensions of size 1:
# a.squeeze().shape  # removes all 1-sized dims, if any

a = torch.rand(1,20,1)
print(a.squeeze().shape)

torch.Size([20])


In [308]:
import numpy as np

In [311]:
a = torch.tensor([1,2,3,4])
a.type()

'torch.LongTensor'

In [314]:
b = a.numpy()
type(b)

numpy.ndarray

In [315]:
c = torch.from_numpy(b)
c.type()

'torch.LongTensor'

In [ ]:
"""Autograd - To calculate derivatives
Autograd is a core component of PyTorch that provides automatic differentiation for tensor ops, enabling gradient
computation using optimization algo like gradient descent."""

In [323]:
import math

x = torch.tensor(3.0, requires_grad=True)

y = x**2

print(x)
print(y)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)


In [324]:
 y.backward() # Calculating Derivative
 x.grad # To see derivative

tensor(6.)

In [326]:
x = torch.tensor(3.0, requires_grad=True)
y = x**2
z = torch.sin(y)

print(x)
print(y)
print(z)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)
tensor(0.4121, grad_fn=<SinBackward0>)


In [327]:
z.backward()

In [328]:
x.grad

tensor(-5.4668)

In [329]:
x = torch.tensor(3.0, requires_grad=True)
y = torch.pow(x, 2)
z = torch.sin(y)

print(x)
print(y)
print(z)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)
tensor(0.4121, grad_fn=<SinBackward0>)


In [330]:
z.backward()

In [331]:
x.grad

tensor(-5.4668)

In [332]:
y.grad

/tmp/ipykernel_92562/4112144004.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:489.)
  y.grad


In [343]:
inp = torch.eye(6, 5, requires_grad=True)
print(inp)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [344]:
test = torch.randn(5, 5)
print(test)
out = torch.matmul(inp, test)
print(out)

tensor([[ 0.0408,  0.2900,  0.0987,  0.4882,  0.5499],
        [-1.7045, -2.6081,  1.4509, -0.0081,  1.9779],
        [ 0.9386, -1.8636,  1.3139, -1.8229, -0.8084],
        [ 0.6715, -0.8192,  0.1258,  1.0674, -0.1175],
        [-0.7096, -0.4763, -1.4336,  0.2672,  0.1090]])
tensor([[ 0.0408,  0.2900,  0.0987,  0.4882,  0.5499],
        [-1.7045, -2.6081,  1.4509, -0.0081,  1.9779],
        [ 0.9386, -1.8636,  1.3139, -1.8229, -0.8084],
        [ 0.6715, -0.8192,  0.1258,  1.0674, -0.1175],
        [-0.7096, -0.4763, -1.4336,  0.2672,  0.1090],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]], grad_fn=<MmBackward0>)


In [340]:
test[-1][-1]==out[0][0]

tensor(False)

# Loss Function

$L = -[y_{target}*\ln(y_{pred}) + (1-y_{target})*\ln(1-y_{pred})]$

In [1]:
import torch

# Inputs
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0) # Weight
b = torch.tensor(0.0) # bias

In [5]:
# Binary cross entropy loss for scalar
def binary_cross_entropy_loss(prediction, target):
    epsilon = 1e-8 # To prevent log(0)
    prediction = torch.clamp(prediction, epsilon, 1-epsilon)
    """" clamp(input, min=None, max=None, *, out=None) -> Tensor
    Clamps all elements in :attr:`input` into the range min and max"""
    return -(target*torch.log(prediction) + (1-target)*torch.log(1-prediction))

In [7]:
# Forward pass
z = w*x +b # Linear part of weighted sum
y_pred = torch.sigmoid(z)

#compute bce loss
loss = binary_cross_entropy_loss(y_pred, y)

In [8]:
loss

tensor(6.7012)

In [10]:
# Backpropagation
# Derivatives:

# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid activation)

dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x
dz_db = 1 # bias contributes directly to z

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [11]:
print(f"Manual Gradient of loss wrt weight (dw): {dL_dw}")
print(f"Manual Gradient of loss wrt bias (db): {dL_db}")

Manual Gradient of loss wrt weight (dw): 6.691762447357178
Manual Gradient of loss wrt bias (db): 0.998770534992218


In [30]:
# Now using autograd doing this same neural network

"""
We do not need to calculate derivative wrt x or y,
so we do not need to use requires_grad while defining x or y
"""
x = torch.tensor(6.7)
y = torch.tensor(0.0)

w = torch.tensor(1.0, requires_grad=True) # Weight
b = torch.tensor(0.0, requires_grad=True) # bias

In [31]:
# Forward Propagation

z = w*x +b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [32]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [33]:
loss = binary_cross_entropy_loss(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [34]:
# Backpropagation

loss.backward()

In [36]:
print(f"Manual Gradient of loss wrt weight (dw): {w.grad}")
print(f"Manual Gradient of loss wrt bias (db): {b.grad}")

Manual Gradient of loss wrt weight (dw): 6.6917619705200195
Manual Gradient of loss wrt bias (db): 0.9987704753875732


In [42]:
# We can also calculate gradient for vectors also
## NB - RuntimeError: Only Tensors of floating point and complex dtype can require gradients

x = torch.tensor([1.,2.,3.], requires_grad=True)
y = (x**2).mean()

y.backward() # Computes partial differentiation wrt vector
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [112]:
# Gradients accumulates, we have to clear grads

x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [117]:
# Forward pass
y = (x**2)
y

tensor(4., grad_fn=<PowBackward0>)

In [118]:
y.backward()

In [119]:
x.grad # The value of x.grad gets add during every pass

tensor(4.)

In [120]:
x.grad.zero_() # After every epoch we clear gradients using this

tensor(0.)

In [121]:
# Also sometime we do not need to calculate derivatives eg in the time of predictions we do not need gradients
# requires_grad takes unnecessary memory space in these situations, we clear it by disabling it
# disable gradient tracking
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [122]:
# Forward pass
y = (x**2)
y

tensor(4., grad_fn=<PowBackward0>)

In [123]:
y.backward()
x.grad

tensor(4.)

##### Option 1: requires_grad_(False)

In [129]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [130]:
x.requires_grad_(False)

tensor(2.)

In [131]:
y = x**2

In [132]:
# y.backward()
# Output: RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

##### Option 2: detach()

In [136]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [137]:
z = x.detach()
z

tensor(2.)

In [138]:
y = x**2
y1 = z**2
print(y)
print(y1)

tensor(4., grad_fn=<PowBackward0>)
tensor(4.)


##### Option 3: torch.no_grad()

In [139]:
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [140]:
with torch.no_grad():
    y = x**2
y

tensor(4.)

In [179]:
# training pipeline

import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [167]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [168]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [169]:
df.shape

(569, 33)

In [170]:
# Remove unwanted columns

df = df.drop(columns=['id','Unnamed: 32'])

In [171]:
df.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [172]:
df.shape

(569, 31)

In [173]:
df.iloc[:,1:] # All rows, from 2nd columns

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [174]:
df.iloc[:,0] # All rows, only first column

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [175]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [176]:
# Scaling

scalar = StandardScaler()
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [177]:
# Label Encoding

# The model might mis-interpret this encoding to be ordinal nature that is 1>0,
# will try to use one-hot encoding here afterward - This is wrong;
# label encoding is appropriate here as we have only two classes i.e. binary - it's just binary to the model
# Models will learn to predict either 0 or 1.; No false ordering issue since there are only two options.
# NB - Most PyTorch loss functions (like nn.BCEWithLogitsLoss or nn.CrossEntropyLoss) expect class labels as integers.

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [178]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,

In [180]:
# Converting all these numpy arrays to torch tensors

X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [182]:
print(X_train_tensor.shape)
print(y_train_tensor.shape)

torch.Size([455, 30])
torch.Size([455])


In [190]:
X_train_tensor[0][0]

tensor(1.0659, dtype=torch.float64)

In [243]:
# Defining the model using python OOP to implement training in pytorch
# We will be using a single neuron here and it will take input directly from our training data
# We have 30 features in our training dataset, so our simple NN here will have 30 weights
# and one bias

class MySimpleNN():
    # defining a constructor
    def __init__(self, X):
        # Creating a weight matrix of size 30x1 (30 input feature); float64 because the training data has same dtype
        self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad=True)
        # As we have only 1 neuron we require only 1 item
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad=True)
    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    # As we are working on a classification problem we will use bce loss
    def loss(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon  = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
        # calculating the mean to find the overall loss
        loss = -(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
        return loss



In [271]:
# defining params

lr = 0.1
epochs = 25

The formula to calculate new weights is -

$ W_{\text{new}} = W_{\text{old}} - lr \cdot \frac{\partial L}{\partial w} $

The formula to calculate new bias is -

$ b_{\text{new}} = b_{\text{old}} - lr \cdot \frac{\partial L}{\partial b} $



In [292]:
# Training pipeline

# create model
# to create a model we have to follow mainly four steps and these four steps will be in a loop of epoch times
# 1. Forward Pass > 2. Calculate Loss > 3. Backpropagation(Differentiation takes place here)
# > 4. Update params like weights and biases

model = MySimpleNN(X_train_tensor)

for epoch in range(epochs):
    # Forward Pass (calculate wx+b and calculate sigmoid)
    y_pred = model.forward(X_train_tensor)

    # calculate loss
    loss = model.loss(y_pred, y_train_tensor)

    # backpropagation
    loss.backward()

    # update params
    # In parameters requires grad is set to true; but in this operation we don't need to calculate the gradient
    with torch.no_grad():
        model.weights -= lr*model.weights.grad
        model.bias -= lr*model.bias.grad

    # And also there is the problem of gradient accumulation so we set the grad to zero in every epoch
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    # if epoch % 100 == 0:
    print(f'Epoch: {epoch+1}, loss: {loss.item()}')



Epoch: 1, loss: 3.148129185176229
Epoch: 2, loss: 3.004326043490834
Epoch: 3, loss: 2.8534408372297495
Epoch: 4, loss: 2.697848265928154
Epoch: 5, loss: 2.5380325604714784
Epoch: 6, loss: 2.374651560305117
Epoch: 7, loss: 2.2067197951913484
Epoch: 8, loss: 2.0408738129576247
Epoch: 9, loss: 1.8820081912762963
Epoch: 10, loss: 1.7277570676791274
Epoch: 11, loss: 1.5762971500954905
Epoch: 12, loss: 1.4315407631045318
Epoch: 13, loss: 1.2992564258639376
Epoch: 14, loss: 1.1802589948636577
Epoch: 15, loss: 1.0790975653381527
Epoch: 16, loss: 0.9963130565914563
Epoch: 17, loss: 0.9313160425095821
Epoch: 18, loss: 0.8823042472925726
Epoch: 19, loss: 0.8465274934061603
Epoch: 20, loss: 0.8208363803800567
Epoch: 21, loss: 0.8022896260938567
Epoch: 22, loss: 0.7885412780109603
Epoch: 23, loss: 0.7779221545743873
Epoch: 24, loss: 0.769331393957299
Epoch: 25, loss: 0.7620764891741735


In [293]:
model.bias

tensor([-0.1603], dtype=torch.float64, requires_grad=True)

In [201]:
print(model.weights.shape)
print(model.bias.shape)

torch.Size([30, 1])
torch.Size([1])


In [301]:
# Evaluation

with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    # y_pred will have value b/w 0 and 1 but we will apply threshold to be able to compare it with original labels
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy:.4f}')


Accuracy: 0.6100
